name: Deploy MkDocs Site

on:
  push:
    branches:
      - docs # Set this to the branch name from which you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.0'  # Set this to the Python version you need
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material  # Install MkDocs and any themes/plugins you need
      - name: Build the MkDocs site
        run: mkdocs build --verbose
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site  # Make sure this directory matches the output of your mkdocs build
          cname: mpythonboard.bitandbrick.com  # Ensure your CNAME matches your subdomain
