name: Deploy MkDocs Site

on:
  push:
    branches:
      - docs # Set this to the branch name from which you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material
    - name: Build MkDocs site
      run: mkdocs build --verbose
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./site
        cname: mpythonboard.bitandbrick.com  # Ensure your CNAME matches your subdomain
